Traceback (most recent call last):
  File "/ext3/miniconda3/envs/cyws3d/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1967, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/ext3/miniconda3/envs/cyws3d/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/ext3/miniconda3/envs/cyws3d/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 47, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/ext3/miniconda3/envs/cyws3d/lib/python3.9/site-packages/transformers/modeling_utils.py", line 41, in <module>
    import torch.distributed.tensor
ModuleNotFoundError: No module named 'torch.distributed.tensor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/ds5725/alvpr/Robust-Scene-Change-Detection/src/scripts/train.py", line 25, in <module>
    import models
  File "/scratch/ds5725/alvpr/Robust-Scene-Change-Detection/src/./models/__init__.py", line 3, in <module>
    from .CD_model import (
  File "/scratch/ds5725/alvpr/Robust-Scene-Change-Detection/src/./models/CD_model.py", line 14, in <module>
    from groundingdino.util.inference import load_model
  File "/scratch/ds5725/alvpr/Robust-Scene-Change-Detection/grounding_dino/groundingdino/util/inference.py", line 12, in <module>
    from grounding_dino.groundingdino.models import build_model
  File "/scratch/ds5725/alvpr/Robust-Scene-Change-Detection/grounding_dino/groundingdino/models/__init__.py", line 8, in <module>
    from .GroundingDINO import build_groundingdino
  File "/scratch/ds5725/alvpr/Robust-Scene-Change-Detection/grounding_dino/groundingdino/models/GroundingDINO/__init__.py", line 15, in <module>
    from .groundingdino import build_groundingdino
  File "/scratch/ds5725/alvpr/Robust-Scene-Change-Detection/grounding_dino/groundingdino/models/GroundingDINO/groundingdino.py", line 24, in <module>
    from transformers import AutoTokenizer, BertModel, BertTokenizer, RobertaModel, RobertaTokenizerFast
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/ext3/miniconda3/envs/cyws3d/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1956, in __getattr__
    value = getattr(module, name)
  File "/ext3/miniconda3/envs/cyws3d/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1955, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/ext3/miniconda3/envs/cyws3d/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1969, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
No module named 'torch.distributed.tensor'
